server {
    listen 80;
    listen [::]:80;
    server_name sallerfix.ru www.sallerfix.ru;

    root /var/www/sallerfix;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico|webp)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }
}
